/**
 * generated by Xtext
 */
package org.jboss.tools.json.ui.contentassist;

import org.jboss.tools.json.ui.contentassist.AbstractJSONProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class JSONProposalProvider extends AbstractJSONProposalProvider {
}
