/*
* generated by Xtext
*/
package org.jboss.tools.json;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JSONUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.jboss.tools.json.ui.internal.JSONActivator.getInstance().getInjector("org.jboss.tools.json.JSON");
	}
	
}
