/**
 * generated by Xtext
 */
package org.jboss.tools.jsoneditor.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class JSONProposalProvider /* implements AbstractJSONProposalProvider  */{
}
