/**
 * generated by Xtext
 */
package org.jboss.tools.json.validation;

import org.jboss.tools.json.validation.AbstractJSONValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JSONValidator extends AbstractJSONValidator {
}
