/*
 * generated by Xtext
 */
package org.jboss.tools.json;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JSONRuntimeModule extends org.jboss.tools.json.AbstractJSONRuntimeModule {

}
