/*
* generated by Xtext
*/
package org.jboss.tools.json;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JSONStandaloneSetup extends JSONStandaloneSetupGenerated{

	public static void doSetup() {
		new JSONStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

